/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package million_dollar_showdown;

import org.junit.Test;
import million_dollar_showdown.model.GameModel;
import static org.junit.Assert.*;

public class AppTest {

   @Test
    public void testExtractFromFile() {
        GameModel questionSelection = new GameModel();
        String question = questionSelection.extractfromfile(1);
        assertNotNull(question);
        assertFalse(question.isEmpty());
    }

    @Test
    public void testExtractQuestion() {
        GameModel questionSelection = new GameModel();
        
        // Test for easy stage (stage 0)
        String easyQuestion = questionSelection.extractquestion(0);
        assertNotNull(easyQuestion);
        assertFalse(easyQuestion.isEmpty());

        // Test for medium stage (stage 6)
        String mediumQuestion = questionSelection.extractquestion(6);
        assertNotNull(mediumQuestion);
        assertFalse(mediumQuestion.isEmpty());

        // Test for hard stage (stage 10)
        String hardQuestion = questionSelection.extractquestion(10);
        assertNotNull(hardQuestion);
        assertFalse(hardQuestion.isEmpty());
    }

    @Test
    public void testOptions() {
        GameModel questionSelection = new GameModel();
        questionSelection.extractfromfile(1);
        assertNotNull(questionSelection.options());
        assertFalse(questionSelection.options().isEmpty());
    }

    @Test
    public void testCheckAnswer() {
        GameModel questionSelection = new GameModel();
        questionSelection.extractfromfile(1);
        assertTrue(questionSelection.checkAnswer(questionSelection.correctAnswer()));
    }
}